// Generated by GG/scripts/sync-game-menus.mjs.
export const GAME_MENU = {
  "selector": "[data-gg-pregame]",
  "steps": {
    "en": [
      "Care for your pet by completing small daily goals and collecting energy.",
      "Tap a goal when you finish it, then send your pet on a walk. Return later to collect the discoveries.",
      "Visit the pet and shop tabs to feed, dress and decorate. Your pet keeps its own chosen species and colors."
    ],
    "ru": [
      "Заботься о питомце: выполняй небольшие ежедневные цели и собирай энергию.",
      "Отмечай выполненные цели и отправляй питомца на прогулку. Вернись позже за находками.",
      "Во вкладках питомца и магазина можно кормить, одевать и украшать комнату. Вид и цвет питомца выбираешь ты."
    ]
  }
}
