// EN translations keyed by exact Russian source string. Russian stays default.
// Populated per-file during the i18n pass.
export const EN: Record<string, string> = {
  ' дел, я тобой так горжусь! Значок уже в твоей коллекции, а памятная табличка ждёт в сумке 🏅': " done, I'm so proud of you! The badge is already in your collection, and a keepsake plaque is waiting in your bag 🏅",
  ' из сундука!': ' from the chest!',
  '! Меня называют питомцем заботы о себе. А что такое забота о себе?': "! They call me a self-care pet. So what is self-care?",
  '(бесплатно)': '(free)',
  '(ты)': '(you)',
  ') поселился у тебя! Загляни в Сумку → Микропитомцы 💛': ') has moved in with you! Check your Bag → Micro-pets 💛',
  '+ Добавить': '+ Add',
  ', а тебя как?': ", and what's your name?",
  ', в сумке! 🎉': ", it's in your bag! 🎉",
  ', забрать': ', collect',
  ', получишь значок и памятную табличку для домика.': ", you'll get a badge and a keepsake plaque for your home.",
  '- нет -': '- none -',
  '-го числа, увидимся в следующем месяце 💛': ', see you next month 💛',
  '«Привет! Привяжи коробочку-сюрприз к одной из своих целей. Выполни её': '"Hi! Attach the surprise box to one of your goals. Complete it',
  '«Рад тебя видеть! Держи горсть косточек, заходи почаще.»': '"Great to see you! Here\'s a handful of bones, come by more often."',
  '· напарники': '· partners',
  '· настроить': '· customize',
  '· сегодня ✓': '· today ✓',
  '· у друга': "· at a friend's",
  '· хочет дружить': '· wants to be friends',
  '·1/день': '·1/day',
  '» пройдено!': '" completed!',
  '», я слышу тебя 💛': '", I hear you 💛',
  'А с': 'And with',
  'Активности': 'Activities',
  'Активные': 'Active',
  'Альпака': 'Alpaca',
  'Аптечка': 'First-aid kit',
  'Архив': 'Archive',
  'Аффирмации': 'Affirmations',
  'БУДКЕА': 'DOGHOUSE',
  'Без значка': 'No badge',
  'Без скрытых платежей': 'No hidden charges',
  'Беру на себя!': "I'm on it!",
  'Беру с собой': 'Take along',
  'Бесплатно, первый полёт 🎉': 'Free, your first flight 🎉',
  'Билет в': 'Ticket to',
  'Билет куплен! Летим, как наберётся энергия ✈️': "Ticket booked! We'll fly once we've saved up energy ✈️",
  'Билет уже куплен, сначала долетим!': "The ticket's already booked, let's finish this flight first!",
  'Больше не друзья': 'No longer friends',
  'Больше уюта и возможностей': 'More coziness and possibilities',
  'В архив': 'To archive',
  'В историю': 'Share to story',
  'В этот день записей нет. Это тоже нормально 💛': "No entries on this day. That's okay too 💛",
  'Вернуть питомца будет нельзя.': "You won't be able to bring your pet back.",
  'Вернуться в «здесь и сейчас», когда мысли уносят. Я рядом.': 'Return to the here and now when your thoughts drift away. I\'m right here.',
  'Вернуться в момент': 'Return to the moment',
  'Вернуться сейчас': 'Return now',
  'Вернётся': 'Returns',
  'Вернётся через': 'Returns in',
  'Весь архив и все 4 газеты в неделю': 'The full archive and all 4 papers per week',
  'Вечерний сбор': 'Evening gathering',
  'Вещь уйдёт из твоей сумки, доставка': 'The item will leave your bag, delivery',
  'Взрослый': 'Adult',
  'Викторины': 'Quizzes',
  'Викторины выключены. Включи их в Настройках, если хочешь мягкие самопроверки.': 'Quizzes are turned off. Turn them on in Settings if you\'d like gentle self-checks.',
  'Викторины-самопроверки': 'Self-check quizzes',
  'Вклад': 'Contribution',
  'Включить напоминания': 'Turn on reminders',
  'Включить паузу': 'Turn on pause',
  'Вопрос': 'Question',
  'Все': 'All',
  'Все важные вещи заботы о себе всегда бесплатны. Плюс, это удобство и красота, а не стена.': "All the important self-care things are always free. Plus is about convenience and beauty, not a paywall.",
  'Все уведомления': 'All notifications',
  'Все уровни пройдены, ты чудо! 🎉': "You've cleared every level, you're wonderful! 🎉",
  'Все цели сделаны! 🎉': 'All goals done! 🎉',
  'Всего выполнено:': 'Total completed:',
  'Вы теперь друзья! 💛': "You're friends now! 💛",
  'Вы уже друзья': "You're already friends",
  'Вы, не разлей вода! 💛': "You two are inseparable! 💛",
  'Выбери друга, который будет расти вместе с тобой.': 'Choose a friend who will grow alongside you.',
  'Выбери цвет': 'Choose a color',
  'Выбери цвет, какой тебе по душе?': 'Pick a color that speaks to you.',
  'Выбери черту для': 'Choose a trait for',
  'Выговориться': 'Vent',
  'Выполняй цели из сфер заботы в разные дни недели:': 'Complete goals from your care areas on different days of the week:',
  'Газеты': 'Newspapers',
  'Готовлю ваш дом…': 'Getting your home ready…',
  'Готово': 'Done',
  'Готово 💛': 'Done 💛',
  'Готово! 💛': 'Done! 💛',
  'Готовы гулять!': 'Ready to walk!',
  'Гуляй со своим питомцем каждый день, каждая прогулка открывает награду': 'Walk with your pet every day, each walk unlocks a reward',
  'Гулять вместе 🐾': 'Walk together 🐾',
  'ДЕНЬ ПОДРЯД': 'DAY STREAK',
  'Да, перепривязать': 'Yes, reattach',
  'Давай узнаем тебя получше!': "Let's get to know you better!",
  'Дай его другу, и вы соседи по Дворику': 'Give it to a friend and you become Yard neighbors',
  'Дальше': 'Next',
  'Движение': 'Movement',
  'Дворик': 'Yard',
  'День': 'Day',
  'День Шарика начинается за пару часов до пробуждения.': "Sharik's day begins a couple of hours before you wake up.",
  'Дневник': 'Journal',
  'Дневник и тёплые вопросы': 'Journal and warm questions',
  'Добавить друга': 'Add a friend',
  'Добавить на главный экран': 'Add to home screen',
  'Добавить цель': 'Add a goal',
  'Доброе дело': 'Good deed',
  'Доброе слово себе': 'A kind word to yourself',
  'Доброта возвращается 💛': 'Kindness comes back around 💛',
  'Добрый, чуткий и заботливый': 'Kind, sensitive, and caring',
  'Долгие цели, по': 'Long-term goals, at',
  'Домик': 'Home',
  'Друг закрыл заявки': "Your friend has closed friend requests",
  'Другу достанется свежий экземпляр со своим номером. Цена подарка': "Your friend gets a fresh copy with its own number. The gift's price is",
  'Дружба с': 'Friendship with',
  'Дружба: уровень': 'Friendship: level',
  'Друзей пришло:': 'Friends arrived:',
  'Друзья увидят, что ты тоже ответил(а) на вопрос дня 💛': "Friends will see that you answered the question of the day too 💛",
  'Дыхание': 'Breathing',
  'Дыхание завершено 💛': 'Breathing complete 💛',
  'Дыхание, дневник, упражнения': 'Breathing, journal, exercises',
  'Ежедневные задания': 'Daily tasks',
  'Если сейчас тяжело': 'If things are hard right now',
  'Ещё': 'More',
  'Ещё не открыто': 'Not unlocked yet',
  'Ещё раз': 'Again',
  'ЗАЯВКИ В ДРУЗЬЯ': 'FRIEND REQUESTS',
  'За вещь вернётся половина её цены. Краску, которую питомец носит прямо сейчас, продать нельзя.': "You'll get back half the item's price. You can't sell the coat your pet is wearing right now.",
  'Заблокирован(а)': 'Blocked',
  'Забота': 'Care',
  'Забота о себе это когда делаешь, что можешь, даже когда тебе непросто.': "Self-care is doing what you can, even when things aren't easy.",
  'Забота о себе это когда заботишься о теле, разуме и отношениях и при этом радуешься жизни!': 'Self-care is caring for your body, mind, and relationships while enjoying life along the way!',
  'Забрать': 'Collect',
  'Забрать прогулку 🦴': 'Collect the walk 🦴',
  'Заведём общего щенка в Шарике? 🐾': "Shall we raise a puppy together in Sharik? 🐾",
  'Завести общего щенка': 'Raise a puppy together',
  'Завести питомца': 'Get a pet',
  'Загляни в Сумку → Мебель, поменяй что-нибудь в домике, а потом вернись сюда.': 'Check your Bag → Furniture, change something in the home, then come back here.',
  'Загляни в Сумку → Одежда, переодень питомца, а потом вернись сюда.': 'Check your Bag → Clothes, dress up your pet, then come back here.',
  'Загляни в любой день': 'Drop by any day',
  'Загружаю друзей…': 'Loading friends…',
  'Загружаю…': 'Loading…',
  'Задания': 'Tasks',
  'Заземление': 'Grounding',
  'Заземлиться': 'Ground yourself',
  'Закончить': 'Finish',
  'Закончить раньше': 'Finish early',
  'Закрепи свою привычку!': 'Lock in your habit!',
  'Заново выбрать питомца и ответить на вопросы. Весь прогресс сохранится.': 'Choose a pet again and answer the questions. All your progress will be saved.',
  'Записано 💛': 'Recorded 💛',
  'Записей пока нет. Начни с любой темы, я подскажу вопросы.': "No entries yet. Start with any topic, I'll suggest questions.",
  'Записей:': 'Entries:',
  'Заходи растить питомца вместе со мной! 💛': 'Come raise a pet with me! 💛',
  'Заявка отправлена ✨': 'Request sent ✨',
  'Заявка уже отправлена': 'Request already sent',
  'Звук и тема': 'Sound and theme',
  'Звуки': 'Sounds',
  'Здесь пока пусто.': "It's empty here for now.",
  'Здесь пока пусто. Питомец делает открытия на прогулках, поговори с ним, когда он вернётся!': "It's empty here for now. Your pet makes discoveries on walks, talk to it when it comes back!",
  'Здесь собрано всё на свете. Купить нельзя, жди, пока вещь появится в витрине. Зато можно посмотреть, что бывает 👀': "Everything in the world is gathered here. You can't buy it, just wait for an item to show up in the shop. But you can browse what exists 👀",
  'Знакомство': 'Getting acquainted',
  'Значки испытаний': 'Challenge badges',
  'Значок для друга': 'A badge for a friend',
  'Зови друзей, награды не кончаются · приглашено:': "Invite friends, the rewards never run out · invited:",
  'Зову друзей…': 'Inviting friends…',
  'Идеи целей': 'Goal ideas',
  'Идём к цели плечом к плечу, по разу в день': 'Heading toward the goal side by side, once a day',
  'Из архива': 'From archive',
  'Из чего складывается твоя забота о себе на этой неделе.': 'What your self-care is made of this week.',
  'Имя питомца': "Pet's name",
  'Имя щенка': "Puppy's name",
  'Инсайты': 'Insights',
  'Испытание «': 'Challenge "',
  'Испытание месяца': 'Challenge of the month',
  'История': 'History',
  'КОД ДРУГА': 'FRIEND CODE',
  'КУПЛЕНО': 'PURCHASED',
  'КУПЛЕНО, уже в твоей сумке 🎒': "PURCHASED, already in your bag 🎒",
  'Как назовём питомца?': 'What shall we name the pet?',
  'Как называть друга?': 'What should we call your friend?',
  'Как отмечать выполнение цели': 'How to mark a goal complete',
  'Как тебе сейчас в целом?': 'How are you feeling overall right now?',
  'Как тебя зовут': "What's your name",
  'Как ты сейчас?': 'How are you right now?',
  'Какое чувство осталось после записи?': 'What feeling stayed with you after writing?',
  'Каталог': 'Catalog',
  'Когда вам собираться?': 'When should you gather?',
  'Код друга': 'Friend code',
  'Код друга скопирован ⧉': 'Friend code copied ⧉',
  'Код не найден': 'Code not found',
  'Код скопирован ✨': 'Code copied ✨',
  'Код скопирован 📋': 'Code copied 📋',
  'Коллекция': 'Collection',
  'Кому подарим?': "Who shall we gift it to?",
  'Копим энергию на прогулку': 'Saving up energy for a walk',
  'Коробочка': 'Little box',
  'Коробочка ждёт, пока ты выберешь цель ниже': 'The box is waiting for you to choose a goal below',
  'Коробочка привязана к цели! 🎁': 'The box is attached to your goal! 🎁',
  'Корова Печенька ждёт тебя': 'Cookie the Cow is waiting for you',
  'Котёнок': 'Kitten',
  'Кто будет твоим питомцем?': 'Who will be your pet?',
  'Кто это будет': 'Who will it be',
  'Кто-то появился!': 'Someone showed up!',
  'Куда это ближе?': 'Which is this closer to?',
  'Купил(а) и подарил(а) спасалочку 🦴': 'Bought and gifted a rescue bone 🦴',
  'Купить за': 'Buy for',
  'Куплено:': 'Purchased:',
  'ЛУЧИКИ': 'RAYS',
  'Лаборатория профессора Овса': "Professor Oats' Lab",
  'Ласковый, спокойный и независимый': 'Affectionate, calm, and independent',
  'Летим в': 'Flying to',
  'Летим! ✈️': "Let's fly! ✈️",
  'Листаем дневник путешествий…': 'Flipping through the travel journal…',
  'Листаем каталог…': 'Flipping through the catalog…',
  'Локации': 'Locations',
  'Лучик': 'Ray',
  'Лучик-комплимент': 'Compliment ray',
  'Лучик-комплимент полетел к': 'A compliment ray flew off to',
  'Лучики приглушены': 'Rays are muted',
  'Лучики, обнимашки, заявки в друзья': 'Rays, hugs, friend requests',
  'Лучшая серия заботы о себе:': 'Best self-care streak:',
  'Лучшая цена': 'Best price',
  'Лёгкая разминка': 'Light warm-up',
  'МОЯ': 'MINE',
  'Магазин': 'Shop',
  'Маленькие шаги заботы': 'Little steps of care',
  'Маленькое добро, большим теплом. Выбери, что сделаешь сегодня.': "A little kindness, with big warmth. Choose what you'll do today.",
  'Малыш': 'Baby',
  'Медитация': 'Meditation',
  'Медитация завершена 💛': 'Meditation complete 💛',
  'Медитация и фокус': 'Meditation and focus',
  'Меню': 'Menu',
  'Местоимения': 'Pronouns',
  'Местоимения питомца': "Pet's pronouns",
  'Микропедия': 'Micropedia',
  'Микропитомец:': 'Micro-pet:',
  'Микропитомцы': 'Micro-pets',
  'Может позже': 'Maybe later',
  'Мои цели': 'My goals',
  'Моя косточка дня в Шарике:': 'My bone of the day in Sharik:',
  'Мудрый, внимательный и чуткий': 'Wise, attentive, and sensitive',
  'Мы вместе растим щенка': "We're raising a puppy together",
  'Мы ещё не включили подписку, наслаждайся всеми возможностями без ограничений.': "We haven't turned on subscriptions yet, enjoy all the features without limits.",
  'Мы завели общего щенка': "We've started raising a puppy together",
  'Мы подросли - теперь': "We've grown up - now",
  'Мы посмотрим. Ещё можно приглушить или заблокировать.': "We'll take a look. You can also mute or block.",
  'Мы растим его вдвоём': "We're raising it together",
  'Мягкая, дружелюбная и забавная': 'Gentle, friendly, and funny',
  'Мягкие опросники о самочувствии': 'Gentle well-being check-ins',
  'Мягко подвигаться вместе с Шариком, 30 секунд на каждое движение.': 'Move gently along with Sharik, 30 seconds per movement.',
  'Мягкое окно на 1.5 часа. Без серий и обратного отсчёта - просто вместе выдохнуть.': "A gentle 1.5-hour window. No streaks, no countdown - just breathe out together.",
  'Мяу! Вот сегодняшние направления. Завтра подберу новые, я кошка непредсказуемая.': "Meow! Here are today's destinations. Tomorrow I'll pick new ones, I'm an unpredictable cat.",
  'На паузе': 'Paused',
  'На паузе серия не прерывается, цели не давят, а Шарик спокойно ждёт. Это забота, а не пропуск.': "While paused, your streak doesn't break, goals don't press, and Sharik waits calmly. This is care, not skipping.",
  'На прогулке': 'On a walk',
  'На прогулку!': "Off for a walk!",
  'На этой неделе ещё нет отметок настроения.': 'No mood check-ins yet this week.',
  'Назад': 'Back',
  'Назвать чувство, уже половина дела. Спасибо, что заглянул(а) внутрь.': 'Naming a feeling is half the work. Thank you for looking inside.',
  'Назови эмоцию': 'Name the emotion',
  'Напиши пару строк…': 'Write a couple of lines…',
  'Напиши питомцу…': 'Write to your pet…',
  'Напоминания от': 'Reminders from',
  'Направления меняются раз в день, обновить за косточки нельзя.': "Destinations change once a day, you can't refresh them with bones.",
  'Например: A1B2C3': 'For example: A1B2C3',
  'Например: выпить воды': 'For example: drink some water',
  'Настроение': 'Mood',
  'Настроение записано 💛': 'Mood recorded 💛',
  'Настройки': 'Settings',
  'Начни день': 'Start the day',
  'Наш малыш': 'Our little one',
  'Наш общий щенок': 'Our shared puppy',
  'Наш щенок 🐾': 'Our puppy 🐾',
  'Наши находки 🔍': 'Our finds 🔍',
  'Не вышло': "That didn't work",
  'Не вышло ответить': "Couldn't reply",
  'Не вышло отправить': "Couldn't send",
  'Не забудь попить воды!': "Don't forget to drink some water!",
  'Не знаешь, с чего начать? Бери готовую, одним касанием.': "Not sure where to start? Grab a ready-made one with a single tap.",
  'Не нравится': "Don't like it",
  'Не получилось': "That didn't work",
  'Не получилось выбрать цвет': "Couldn't pick the color",
  'Не получилось добавить': "Couldn't add",
  'Не получилось забрать, попробуй ещё раз': "Couldn't collect, try again",
  'Не получилось записать настроение, попробуй ещё раз': "Couldn't record your mood, try again",
  'Не получилось купить билет': "Couldn't buy the ticket",
  'Не получилось открыть оплату': "Couldn't open payment",
  'Не получилось подключиться': "Couldn't connect",
  'Не получилось принять': "Couldn't accept",
  'Не получилось, попробуй ещё раз': "That didn't work, try again",
  'Не сейчас': 'Not now',
  'Не сохранилось': "Didn't save",
  'Не удалось загрузить': 'Failed to load',
  'Не удалось загрузить Дворик 🌿': 'Failed to load the Yard 🌿',
  'Не хватает косточек 🦴': 'Not enough bones 🦴',
  'Не хватает 🦴': 'Not enough 🦴',
  'Недельные звёзды': 'Weekly stars',
  'Неспешная, надёжная и стойкая': 'Unhurried, reliable, and steadfast',
  'Несу твои задания… ✨': 'Bringing your tasks… ✨',
  'Ничего не спишется': "Nothing will be charged",
  'Новое имя…': 'New name…',
  'Новые места ждут в турбюро «Хвост-трэвел» ✈️': 'New places await at the Tail-Travel agency ✈️',
  'Новый микропитомец (': 'New micro-pet (',
  'Нравится': 'Like it',
  'Нужен отдых?': 'Need a rest?',
  'Обнимашка отправлена 🤗 (друзей пока нет)': "Hug sent 🤗 (no friends yet)",
  'Обнимашка разлетелась': 'The hug spread around',
  'Обновить': 'Refresh',
  'Обнять питомца 🤗': 'Hug your pet 🤗',
  'Обои': 'Wallpaper',
  'Общая цель': 'Shared goal',
  'Общие цели': 'Shared goals',
  'Одежда': 'Clothes',
  'Одно дело в день, в любом порядке. Пройдёшь все': 'One task a day, in any order. Complete them all',
  'Окрасы': 'Colorways',
  'Оплата пока недоступна': 'Payment is not available yet',
  'Особые вещицы ограниченного тиража. У каждой свой номер. Прозрачно: видно, сколько уже разобрали. Можно подарить другу.': "Special limited-edition items. Each has its own number. Transparent: you can see how many are already taken. You can gift one to a friend.",
  'Особые задания': 'Special tasks',
  'Оставить': 'Keep',
  'Остались награды прошлого месяца:': "Last month's rewards are still available:",
  'Осталось': 'Remaining',
  'Остаться': 'Stay',
  'От': 'From',
  'Ответить': 'Reply',
  'Ответить лучиком 🌟': 'Reply with a ray 🌟',
  'Отдохнуть без потери серии': 'Rest without losing your streak',
  'Отклонено': 'Declined',
  'Отклонить': 'Decline',
  'Откроется на стадии': 'Unlocks at stage',
  'Откроется на стадии «': 'Unlocks at the "',
  'Открой в Шарик Плюс, старые выпуски и больше рубрик.': 'Unlock with Sharik Plus, back issues and more sections.',
  'Открываем дневник…': 'Opening the journal…',
  'Открываем сумку…': 'Opening the bag…',
  'Открываем сундук…': 'Opening the chest…',
  'Открываю витрину…': 'Opening the shop…',
  'Открываю сумку…': 'Opening the bag…',
  'Открываю ящик…': 'Opening the box…',
  'Открытие:': 'Discovery:',
  'Открытия': 'Discoveries',
  'Открыто': 'Unlocked',
  'Открыть': 'Open',
  'Открыть Шарика': 'Open Sharik',
  'Открыть подарок': 'Open the gift',
  'Откуда ты узнал(а) о нас?': 'How did you hear about us?',
  'Отмена': 'Cancel',
  'Отметить выполненным': 'Mark as done',
  'Отмечай настроение на главном экране, здесь появится твоя картинка.': "Check in your mood on the home screen, and your picture will appear here.",
  'Отправить другу': 'Send to a friend',
  'Отправить за': 'Send for',
  'Отправить ссылку': 'Send the link',
  'Отправь ссылку другу - как только он откроет, щенок вылупится у вас обоих.': "Send the link to a friend - as soon as they open it, the puppy hatches for you both.",
  'Отпустить': 'Let go',
  'Оформить за': 'Get it for',
  'Очистить всё': 'Clear all',
  'ПЛЮС': 'PLUS',
  'ПРИГЛАШЕНИЯ К ОБЩЕЙ ЦЕЛИ': 'SHARED GOAL INVITATIONS',
  'Пауза': 'Pause',
  'Пауза включена. Отдыхай 💛': 'Pause is on. Take a rest 💛',
  'Пауза двора': 'Yard pause',
  'Пауза заканчивается сегодня.': 'The pause ends today.',
  'Первый полёт, за счёт Сасси!': "Your first flight, on Sassy!",
  'Переименовали 💛': 'Renamed 💛',
  'Переименовать': 'Rename',
  'Перемешать': 'Shuffle',
  'Перепривязать коробочку к «': 'Reattach the box to "',
  'Питомцу было важно поделиться этим с тобой.': 'It mattered to your pet to share this with you.',
  'Пиши о чём угодно, я просто рядом и слушаю. Чем больше напишешь, тем больше энергии (4-8⚡).': "Write about anything, I'm just here listening. The more you write, the more energy (4-8⚡).",
  'Плюс ⭐': 'Plus ⭐',
  'Повседневная коллекция': 'Everyday collection',
  'Повторяю 🌞': 'Repeating 🌞',
  'Поговорить с питомцем': 'Talk to your pet',
  'Поговорить с человеком': 'Talk to a person',
  'Подарил(а)': 'Gifted',
  'Подарить': 'Give a gift',
  'Подарок отправлен! 🎁': 'Gift sent! 🎁',
  'Подарок №': 'Gift #',
  'Подарочек от Колюча!': 'A little gift from Prickly!',
  'Поддержи Шарика и получи больше уюта': 'Support Sharik and get more coziness',
  'Поделиться': 'Share',
  'Поделиться в истории 💛': 'Share to your story 💛',
  'Поделиться ссылкой (можно с новым другом)': 'Share a link (you can with a new friend)',
  'Поделиться целью': 'Share the goal',
  'Поделиться 💛': 'Share 💛',
  'Подружиться': 'Become friends',
  'Подыши вместе со мной, круг покажет ритм.': 'Breathe along with me, the circle will show the rhythm.',
  'Поехали!': "Let's go!",
  'Пожаловаться': 'Report',
  'Позвал(а)': 'Invited',
  'Позвать в гости на час 🏡': 'Invite over for an hour 🏡',
  'Позвать друга': 'Invite a friend',
  'Познакомься с Коровой Печенькой': 'Meet Cookie the Cow',
  'Позови друзей, и получи микропитомцев по дороге': 'Invite friends and collect micro-pets along the way',
  'Пока не получилось починить серию': "Couldn't fix the streak yet",
  'Пока некому дарить, загляни во «Дворик» и добавь друзей 💛': "No one to gift to yet, visit the Yard and add friends 💛",
  'Пока нет значков, загляни в задания, там ждут испытания! 🏅': "No badges yet, check the tasks, challenges await! 🏅",
  'Пока никого рядом': 'No one around yet',
  'Пока никто не присылал лучиков. Пошли первым!': "No one's sent any rays yet. Be the first!",
  'Пока ничего нет, загляни в магазин 🛍️': "Nothing here yet, check the shop 🛍️",
  'Пока пусто, но всё впереди.': "Empty for now, but it's all ahead.",
  'Пока пусто, открытия появляются после прогулок и бесед с питомцем ✨': "Empty for now, discoveries appear after walks and chats with your pet ✨",
  'Пока тихо, но скоро будут новости ✨': "Quiet for now, but news is coming soon ✨",
  'Пока тут только твой питомец, получи первого друга!': "It's just your pet here for now, get your first friend!",
  'Покормите щенка вдвоём, чтобы пойти гулять': 'Feed the puppy together to go for a walk',
  'Полетели в': 'Flying to',
  'Полетим, как только питомец наберёт энергию на прогулку.': "We'll fly as soon as your pet saves up enough energy for a walk.",
  'Получено': 'Received',
  'Получено:': 'Received:',
  'Полы': 'Floors',
  'Полы и обои': 'Floors and wallpaper',
  'Помахал(а)': 'Waved',
  'Помодоро-таймер: одно дело, без отвлечений.': 'Pomodoro timer: one task, no distractions.',
  'Поможешь растить щенка в Шарике? 🐾': 'Will you help raise a puppy in Sharik? 🐾',
  'Понять, что чувствуешь': 'Understand what you feel',
  'Попробовать ещё раз': 'Try again',
  'Попробуй эти простые цели с': 'Try these simple goals with',
  'Попросить обнимашку': 'Ask for a hug',
  'Похвалил(а) друга! 👏': 'Praised a friend! 👏',
  'Починить серию': 'Fix the streak',
  'Почта': 'Mail',
  'Почта пустая 📭': 'Mailbox is empty 📭',
  'Пошли гулять вместе! 🐾': "Let's go for a walk together! 🐾",
  'Пошли тёплый лучик': 'Send a warm ray',
  'Праздничные ивенты и наряды': 'Festive events and outfits',
  'Предложение отправлено другу': 'Invitation sent to your friend',
  'Предпочтения': 'Preferences',
  'Привет! Спасибо, что выбрал(а) меня! Меня зовут': "Hi! Thank you for choosing me! My name is",
  'Привяжи свои цели к сферам заботы, и каждую неделю здесь будут появляться звёзды ⭐': 'Link your goals to care areas, and stars will appear here every week ⭐',
  'Привяжи цели к сферам заботы, чтобы видеть прогресс.': 'Link goals to care areas to see your progress.',
  'Привязать к цели': 'Attach to a goal',
  'Пригласить': 'Invite',
  'Приглашение к общей цели отправлено! 🤝': 'Shared goal invitation sent! 🤝',
  'Приглашение отправлено! 💛': 'Invitation sent! 💛',
  'Приглашение уже неактуально': 'This invitation is no longer valid',
  'Примерочная': 'Fitting room',
  'Принимаю заявки в друзья': 'Accepting friend requests',
  'Принимаю тёплые лучики': 'Accepting warm rays',
  'Принял(а) вызов! 🤝': 'Challenge accepted! 🤝',
  'Принять': 'Accept',
  'Прислушаться к себе': 'Listen to yourself',
  'Присоединиться': 'Join',
  'Присоединиться можно до': 'You can join until',
  'Приятно познакомиться,': 'Nice to meet you,',
  'Прогресс коробочки сбросится до 0 /': "The box's progress will reset to 0 /",
  'Прогулка': 'Walk',
  'Прогулка!': 'Walk!',
  'Продано за': 'Sold for',
  'Продать': 'Sell',
  'Продать «': 'Sell "',
  'Продолжить': 'Continue',
  'Продышаться': 'Catch your breath',
  'Произнеси вслух или про себя, и нажми после каждого раза': 'Say it aloud or to yourself, and tap after each time',
  'Пройдено! Значок твой 🏅': "Completed! The badge is yours 🏅",
  'Пропустить': 'Skip',
  'Пропустить и сохранить': 'Skip and save',
  'Просто выговориться. 4-8⚡, чем больше напишешь, тем больше энергии.': "Just vent. 4-8⚡, the more you write, the more energy.",
  'Просятся вернуться': 'Asking to come back',
  'Профиль': 'Profile',
  'Прочитано': 'Read',
  'Прошлое событие, награды можно забрать до': 'Past event, rewards can be collected until',
  'Прошлые выпуски появятся здесь по понедельникам.': 'Past issues will appear here on Mondays.',
  'Пусть эти слова будут с тобой 💛': 'May these words stay with you 💛',
  'Путешествия': 'Travels',
  'Раз в день:': 'Once a day:',
  'Размышления': 'Reflections',
  'Размялись! 💛': 'Warmed up! 💛',
  'Разобрали': 'Taken',
  'Разобрано': 'Taken',
  'Раскладываем товары…': 'Setting out the goods…',
  'Раскопать косточку дня': 'Dig up the bone of the day',
  'Растим': 'Raising',
  'Растим вдвоём 🐣': 'Raising together 🐣',
  'Растите его вдвоём: он подрастает, только когда оба зашли. Никаких штрафов - просто общее тепло 💛': 'Raise it together: it grows only when you both check in. No penalties - just shared warmth 💛',
  'Режим дня': 'Daily routine',
  'С возвращением! 💛': 'Welcome back! 💛',
  'С кем растим': 'Who we raise with',
  'С приложением на главном экране держать привычки': 'Keep up habits with the app on your home screen',
  'СВЕЖИЙ ВЫПУСК': 'FRESH ISSUE',
  'Сасси': 'Sassy',
  'Сасси откроет двери, когда питомец немного подрастёт и сможет летать.': "Sassy will open the doors once your pet grows a bit and can fly.",
  'Сасси раскладывает билеты…': 'Sassy is laying out the tickets…',
  'Свернуть': 'Collapse',
  'Свободная запись': 'Free writing',
  'Свои эмодзи, в Плюсе': 'Custom emoji, in Plus',
  'Свой ответ останется между вами, открытие в дневник не запишется.': "Your answer stays between you, the discovery won't be recorded in the journal.",
  'Сделал(а)': 'Did it',
  'Сегодня': 'Today',
  'Сегодня вы уже гуляли вместе. Энергия копится дальше, а новая прогулка будет завтра.': "You've already walked together today. Energy keeps building, and a new walk comes tomorrow.",
  'Сегодня друзья выкопали:': 'Today your friends dug up:',
  'Сегодня можно полегче. Загляни сюда, если тяжело.': "Today can be easier. Come here if things are hard.",
  'Сегодня уже гуляли 🌙': "Already walked today 🌙",
  'Сегодня уже дарил(а)': 'Already gifted today',
  'Сегодня уже обнимались 🤗': 'Already hugged today 🤗',
  'Сегодня уже отмечено, продолжим завтра 💛': "Already checked in today, we'll continue tomorrow 💛",
  'Сегодня я…': 'Today I…',
  'Сезонные события': 'Seasonal events',
  'Сейчас всё открыто бесплатно 💛': 'Everything is free right now 💛',
  'Сейчас вы в:': "You're currently in:",
  'Сейчас нельзя': "Can't right now",
  'Сейчас: подъём': 'Now: wake-up',
  'Серия восстановлена! 🌞': 'Streak restored! 🌞',
  'Серия и цели заморожены до': 'Streak and goals are frozen until',
  'Серия прервалась, бывает! 💛': 'The streak broke, it happens! 💛',
  'Сколько дней подряд ты будешь заботиться о': 'How many days in a row will you care for',
  'Сколько минут': 'How many minutes',
  'Слонёнок': 'Baby elephant',
  'Сначала добавь цель на главном экране, и возвращайся!': 'First add a goal on the home screen, then come back!',
  'Сначала заведи друга во Дворике 💛': 'First make a friend in the Yard 💛',
  'Сначала заведи цель на Главной 🌱': 'First set a goal on the Home screen 🌱',
  'Снова слышишь друга': "You can hear your friend again",
  'Снять': 'Remove',
  'Снять паузу': 'Unpause',
  'Совёнок': 'Baby owl',
  'Создать ссылку': 'Create a link',
  'Сохранено 💛': 'Saved 💛',
  'Сохранить': 'Save',
  'Сохранить картинку': 'Save the image',
  'Спасибо!': 'Thank you!',
  'Спасибо! Шарик Плюс активирован 💛': 'Thank you! Sharik Plus is activated 💛',
  'Спасибо, мы посмотрим 🙏': "Thanks, we'll take a look 🙏",
  'Спасибо, что прислушался(ась) к себе 💛': 'Thank you for listening to yourself 💛',
  'Спокойной ночи 🌙': 'Good night 🌙',
  'Стартовый план': 'Starter plan',
  'Стоимость:': 'Cost:',
  'Студия окраса': 'Color studio',
  'Сумка питомца': "Pet's bag",
  'Сумка пока пустая 🎒': 'The bag is empty for now 🎒',
  'Сфера заботы': 'Care area',
  'Сферы заботы': 'Care areas',
  'Таймеры': 'Timers',
  'Твои питомцы': 'Your pets',
  'Твой вклад': 'Your contribution',
  'Твой код': 'Your code',
  'Твой новый друг для заботы о себе.': 'Your new self-care companion.',
  'Твой экземпляр №': 'Your copy #',
  'Твоё имя': 'Your name',
  'Тема оформления': 'Theme',
  'Теперь': 'Now',
  'Теперь вы друзья! 💛': "You're friends now! 💛",
  'Тепло другим, тепло себе': 'Warmth to others, warmth to yourself',
  'Тихие звуки заботы о Шарике': 'Quiet sounds of caring for Sharik',
  'Тихо выдохнуть перед сном': 'Breathe out quietly before sleep',
  'Тихое время с Шариком.': 'Quiet time with Sharik.',
  'Только здесь:': 'Only here:',
  'Точно отпустить': 'Really let go',
  'Турбюро пока закрыто': 'The travel agency is closed for now',
  'Ты в деле! 🎉': "You're in! 🎉",
  'Ты здесь 💛': "You're here 💛",
  'Ты здесь, ты в безопасности 💛': "You're here, you're safe 💛",
  'Ты на паузе': "You're paused",
  'Ты сделал(а) все ': 'You did all ',
  'Ты справляешься 💛': "You're doing great 💛",
  'Ты ушёл из двора. Щенок остаётся другу 💛': "You've left the yard. The puppy stays with your friend 💛",
  'Тёплые слова': 'Warm words',
  'Тёплые слова, которые щенок доставит лично 💛': 'Warm words the puppy will deliver in person 💛',
  'Тёплый лес': 'Warm forest',
  'Тёплый лучик для': 'A warm ray for',
  'Тёплый лучик согреет друга, а тебе за первый за день:': 'A warm ray will warm your friend, and for your first of the day you get:',
  'Тёплый, преданный и любопытный': 'Warm, devoted, and curious',
  'У': 'For',
  'У вас уже 3 общих щенка': 'You already have 3 shared puppies',
  'У нас вылупился': 'We hatched',
  'У тебя всё получится!': "You've got this!",
  'У тебя получится!': "You've got this!",
  'Уведомления': 'Notifications',
  'Уведомления о Дворике': 'Yard notifications',
  'Удалить': 'Delete',
  'Удалить из друзей': 'Remove from friends',
  'Удалить совсем? История этой цели исчезнет.': "Delete for good? This goal's history will disappear.",
  'Удалить цель': 'Delete the goal',
  'Уже есть, продали за': 'Already have it, sold for',
  'Уйти': 'Leave',
  'Ура!': 'Hooray!',
  'Ура! 🎉': 'Hooray! 🎉',
  'Уровень': 'Level',
  'Успокоиться за пару минут': 'Calm down in a couple of minutes',
  'Ух ты! Когда ты заботишься о себе, ты заботишься и обо мне! Давай вместе!': "Wow! When you take care of yourself, you take care of me too! Let's do it together!",
  'Фокус': 'Focus',
  'Фокус-сессия завершена 💛': 'Focus session complete 💛',
  'Характер растёт из твоих ответов на прогулках ✨': 'Character grows from your answers on walks ✨',
  'Характер:': 'Character:',
  'Хвост-трэвел': 'Tail-Travel',
  'Хвост-трэвел · Сасси': 'Tail-Travel · Sassy',
  'Цвет коробочки': 'Box color',
  'Цвет яйца': 'Egg color',
  'Целей на сегодня:': 'Goals for today:',
  'Целей пока нет. Добавь их на главном экране или из «Идей целей».': 'No goals yet. Add them on the home screen or from "Goal ideas".',
  'Цели': 'Goals',
  'Цель': 'Goal',
  'Цель добавлена 💛': 'Goal added 💛',
  'Цель на паузе': 'Goal paused',
  'Цель снова активна': 'Goal is active again',
  'Цель теперь общая ⭐': 'The goal is now shared ⭐',
  'Цель удалена': 'Goal deleted',
  'Цена вещи +': "Item's price +",
  'Чаще всего': 'Most often',
  'Черепашка': 'Little turtle',
  'Что ближе всего?': "What's closest?",
  'Что нового': "What's new",
  'Что питомец любит и не любит, узнаётся в беседах после прогулок': 'What your pet likes and dislikes is revealed in chats after walks',
  'Шаг': 'Step',
  'Шарик': 'Sharik',
  'Шарик Плюс': 'Sharik Plus',
  'Шарик Плюс на целый год': 'Sharik Plus for a whole year',
  'Шарик Плюс оплачивается звёздами Telegram и только когда ты сам(а) захочешь. Никаких автосписаний и карт.': "Sharik Plus is paid with Telegram Stars and only when you choose to. No auto-charges, no cards.",
  'Шарик бесплатный навсегда': 'Sharik is free forever',
  'Шарик дремлет, пока ты в деле. Сосредоточься на одном.': "Sharik dozes while you're at it. Focus on one thing.",
  'Шарик отдыхает рядом. Просто будь здесь.': 'Sharik rests beside you. Just be here.',
  'Шарик подождёт тебя и не будет грустить. Отдыхай столько, сколько нужно.': "Sharik will wait for you and won't be sad. Rest as long as you need.",
  'Шарик просыпается…': 'Sharik is waking up…',
  'Шарик это развлекательное приложение для заботы о себе в игровой форме. Это не медицинская или психологическая услуга, и оно не заменяет консультацию специалиста. Если тебе тяжело, пожалуйста, обратись за профессиональной помощью.': "Sharik is an entertainment app for self-care in a playful form. It is not a medical or psychological service, and it does not replace a consultation with a specialist. If you're struggling, please seek professional help.",
  'Шарик это развлекательное приложение для заботы о себе. Не является медицинской или психологической услугой и не заменяет консультацию специалиста.': "Sharik is an entertainment app for self-care. It is not a medical or psychological service and does not replace a consultation with a specialist.",
  'Щенок': 'Puppy',
  'Щенок вылупился! 🐣': 'The puppy hatched! 🐣',
  'Эта витрина откроется с «Шарик Плюс» ⭐': 'This shop unlocks with Sharik Plus ⭐',
  'Эти вещи всегда в наличии, выбирай любой цвет.': 'These items are always in stock, pick any color.',
  'Это можно поменять позже.': 'You can change this later.',
  'Это разовая оплата за 365 дней, не ежемесячно. Отменять ничего не нужно.': "This is a one-time payment for 365 days, not monthly. There's nothing to cancel.",
  'Это твой код 🙂': "That's your own code 🙂",
  'Этот лучик для Plus 🔒': 'This ray is for Plus 🔒',
  'Я делаю достаточно.': "I'm doing enough.",
  'Я укладываю щенка 🌙': "I'm putting the puppy to bed 🌙",
  'будет видеть твой стрик': 'will see your streak',
  'в': 'in',
  'в 4 раза проще.': '4 times easier.',
  'в Шарике 🐣': 'in Sharik 🐣',
  'в Шарике 🐾': 'in Sharik 🐾',
  'в восторге! 💙': 'is thrilled! 💙',
  'в гости на час 🏡': 'over for an hour 🏡',
  'в гостях ещё': 'visiting for another',
  'в месяц': 'per month',
  'в ответ!': 'in return!',
  'вдвоём!': 'together!',
  'вдох': 'breathe in',
  'вернулся с прогулки!': 'is back from a walk!',
  'вопросов': 'questions',
  'выдох': 'breathe out',
  'выкопал': 'dug up',
  'да 💛': 'yes 💛',
  'движений': 'movements',
  'день': 'day',
  'день подряд': 'day streak',
  'дн вместе': 'days together',
  'дн вместе 🔥': 'days together 🔥',
  'дн назад': 'days ago',
  'дн подряд': 'day streak',
  'дн.': 'd',
  'дн. на неделе': 'd this week',
  'дней': 'days',
  'дней вместе!': 'days together!',
  'дней подряд': 'days in a row',
  'дней подряд растим общего щенка вдвоём 🔥': 'days in a row raising a puppy together 🔥',
  'дня': 'days',
  'дня подряд': 'day streak',
  'друг': 'friend',
  'друга': 'friend',
  'друзей укладывают щенков': 'friends are putting puppies to bed',
  'друзьям 🌙': 'friends 🌙',
  'друзьям 🤗': 'friends 🤗',
  'есть': 'have',
  'ждёт ответа на лучик уже': 'has been waiting for a reply to a ray for',
  'ждёт, пока вы соберётесь вдвоём 💛': 'is waiting for you two to gather 💛',
  'за то, что поделился 💛': 'for sharing 💛',
  'за тёплый разговор': 'for a warm chat',
  'заботы ещё больше': 'even more care',
  'записано в дневник открытий': 'recorded in the discovery journal',
  'записей:': 'entries:',
  'заработано наград:': 'rewards earned:',
  'звёзд за весь год': 'stars for the whole year',
  'зовёт к общей цели': 'invites you to a shared goal',
  'зовёт растить общего щенка': 'invites you to raise a puppy together',
  'из': 'of',
  'из локации «': 'from the location "',
  'каждому 🦴': 'each 🦴',
  'косточку': 'a bone',
  'косточку-спасалочку 🦴': 'a rescue bone 🦴',
  'куплен!': 'purchased!',
  'маленьких дел за месяц': 'small deeds this month',
  'малыш': 'baby',
  'мин': 'min',
  'мин назад': 'min ago',
  'мин, загляни в комнату!': 'min, check the room!',
  'на год · выгоднее': 'per year · better value',
  'на прогулке': 'on a walk',
  'на прогулке!': 'on a walk!',
  'написать кому-то тёплое сообщение': 'write someone a warm message',
  'не нравится': 'dislikes',
  'не оценил… ❤️‍🩹': "didn't appreciate it… ❤️‍🩹",
  'нет': 'no',
  'нравится': 'likes',
  'один вопрос': 'one question',
  'останется дома 🏡': 'will stay home 🏡',
  'отбой': 'lights out',
  'открытий:': 'discoveries:',
  'открыто': 'unlocked',
  'отметок:': 'check-ins:',
  'отправился на волю. Спасибо за всё! 🌿': 'set off into the wild. Thank you for everything! 🌿',
  'отправлен': 'sent',
  'очков дружбы': 'friendship points',
  'питомец': 'pet',
  'поблагодарить близкого человека': 'thank someone close to you',
  'подрос в Шарике! 🎉': 'grew up in Sharik! 🎉',
  'подрос(ла) до': 'grew up to',
  'пойдёт на прогулку! 🌳': 'is off for a walk! 🌳',
  'полетел к': 'flew off to',
  'получил(а)': 'received',
  'починка': 'fix',
  'починки': 'fixes',
  'починок': 'fixes',
  'почти дома': 'almost home',
  'предложить помощь тому, кому трудно': 'offer help to someone who is struggling',
  'прогулка': 'walk',
  'прогулок': 'walks',
  'прогулок:': 'walks:',
  'раз - и внутри окажется новый друг. Кто именно, сюрприз даже для меня!»': 'times - and a new friend will be inside. Who exactly, is a surprise even to me!"',
  'раз в день': 'once a day',
  'растёт с нами': 'grows with us',
  'с': 'with',
  'с стадии «': 'from the "',
  'с тобой!': 'with you!',
  'с целями на этой неделе': 'with goals this week',
  'само': 'itself',
  'сделано сегодня': 'done today',
  'сделать искренний комплимент': 'give a heartfelt compliment',
  'сделать что-то доброе для себя': 'do something kind for yourself',
  'сегодня': 'today',
  'сейчас': 'now',
  'серия под угрозой. Подаришь косточку-спасалочку?': 'streak is at risk. Will you gift a rescue bone?',
  'следующий за': 'next after',
  'тепло:': 'warm:',
  'только что': 'just now',
  'тяжело:': 'hard:',
  'уже есть': 'already have it',
  'уже подарено': 'already gifted',
  'ур.': 'lv.',
  'уровень': 'level',
  'характер:': 'character:',
  'хозяин': 'owner',
  'хочет понять, как расти вместе с тобой.': 'wants to understand how to grow alongside you.',
  'целей': 'goals',
  'целей:': 'goals:',
  'цель': 'goal',
  'ценит…': 'values…',
  'ч': 'h',
  'ч назад': 'h ago',
  'что-нибудь да найдёт · 1 раз в день': "is bound to find something · once a day",
  'шагов': 'steps',
  '‹ Дворик': '‹ Yard',
  '‹ Назад': '‹ Back',
  '← Вернуться к текущему событию': '← Back to the current event',
  '← Назад к вариантам': '← Back to options',
  '↩ Вернуть': '↩ Restore',
  '−50% сегодня:': '−50% today:',
  '⏸ Пауза': '⏸ Pause',
  '▦ Сетка': '▦ Grid',
  '▶ Возобновить': '▶ Resume',
  '☰ Список': '☰ List',
  '⚙️ Настройки Дворика': '⚙️ Yard settings',
  '⚠️ Билет в один конец: вернуться можно будет, только когда город снова появится у Сасси. Полёт займёт место сегодняшней прогулки (или завтрашней, если питомец уже гулял).': "⚠️ One-way ticket: you'll only be able to return once the city appears at Sassy's again. The flight takes the place of today's walk (or tomorrow's, if your pet already walked).",
  '✈️ Билет за': '✈️ Ticket for',
  '✈️ Лететь бесплатно': '✈️ Fly for free',
  '✍️ Свой ответ': '✍️ Your own answer',
  '✏️ Переименовать': '✏️ Rename',
  '✓ В целях': '✓ In goals',
  '✨ Краски открываются по мере роста питомца:': '✨ Colors unlock as your pet grows:',
  '✨ Открыть колонку Плюс': '✨ Unlock the Plus column',
  '✨ Открыть!': '✨ Unlock!',
  '❤️ Тёплые лучики': '❤️ Warm rays',
  '⭐ Поделиться целью': '⭐ Share the goal',
  '⭐ С «Шарик Плюс» здесь была бы вещь со скидкой −50% и ещё 6 витрин ниже.': '⭐ With Sharik Plus there would be an item at −50% here and 6 more shops below.',
  '⭐ на год': '⭐ per year',
  '⭐/мес': '⭐/mo',
  '⭐/мес вместо': '⭐/mo instead of',
  '＋ Добавить друга': '＋ Add a friend',
  '🌅 Подъём': '🌅 Wake-up',
  '🌙 Вечерний сбор в': '🌙 Evening gathering at',
  '🌙 Отбой': '🌙 Lights out',
  '🌞 Лучшая серия': '🌞 Best streak',
  '🌟 Взрослый': '🌟 Adult',
  '🌟 Послать тёплый лучик': '🌟 Send a warm ray',
  '🌱 Возраст': '🌱 Age',
  '🌳 Взять на прогулку': '🌳 Take for a walk',
  '🌳 Прогулка началась': '🌳 The walk has begun',
  '🌳 Прогулка состоялась': '🌳 The walk happened',
  '🌳 Прогулок': '🌳 Walks',
  '🌿 Отпустить на волю': '🌿 Release into the wild',
  '🌿 Спокойно': '🌿 Calm',
  '🍼 Вечный малыш: вкл, выключить': '🍼 Forever baby: on, turn off',
  '🍼 Вечный малыш: выкл, включить': '🍼 Forever baby: off, turn on',
  '🍼 Малыш': '🍼 Baby',
  '🎁 Подарить': '🎁 Give a gift',
  '🎁 Подарить другу': '🎁 Gift to a friend',
  '🎁 привязано': '🎁 attached',
  '🎂 День рождения': '🎂 Birthday',
  '🎉 Радоваться': '🎉 Celebrate',
  '🏡 Оставить дома': '🏡 Keep at home',
  '🐾 Шарик · заведи своего щенка': '🐾 Sharik · get your own puppy',
  '👋 Пожелать всем спокойной ночи': '👋 Wish everyone good night',
  '👤 Отправить от своего имени': '👤 Send under your own name',
  '💌 Комплимент': '💌 Compliment',
  '💫 Характер': '💫 Character',
  '📋 Скопировать код': '📋 Copy the code',
  '📨 Позвать друга': '📨 Invite a friend',
  '📨 Пригласить нового': '📨 Invite a new one',
  '🔄 Обновить витрину': '🔄 Refresh the shop',
  '🔄 Пройти знакомство заново': '🔄 Redo the intro',
  '🔔 Включить лучики': '🔔 Turn on rays',
  '🔕 Приглушить лучики': '🔕 Mute rays',
  '🔢 Ввести код друга': '🔢 Enter a friend code',
  '🗄 В архив': '🗄 To archive',
  '😊 Значок-эмодзи': '😊 Emoji badge',
  '🙈 Тайный лучик (друг не узнает, кто)': "🙈 Secret ray (your friend won't know who)",
  '🚩 Пожаловаться': '🚩 Report',
  '🚫 Заблокировать': '🚫 Block',
  '🤝 Общая цель': '🤝 Shared goal',
  '🥚 …или заведите общего щенка вместе': '🥚 …or raise a puppy together',
  '🦴 Косточек собрано': '🦴 Bones collected',
  '🦴 Спасалочка': '🦴 Rescue bone',
  '🦴 за доставку': '🦴 for delivery',
  '🦴 за каждый уровень': '🦴 per level',
  '🦴. Вещь уйдёт из сумки.': '🦴. The item will leave your bag.',
  '🪪 Показать мой код': '🪪 Show my code',
}
